# Generated by Django 4.2.5 on 2024-01-25 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_day', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=2047)),
                ('location', models.CharField(max_length=2047)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_dates',
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ManyToManyField(blank=True, to='sale.event'),
        ),
    ]
