# Generated by Django 4.2.5 on 2024-03-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_event_status_orderitem_custom_price_and_more'),
        ('sale', '0003_remove_order_client_remove_order_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale.invoice.invoiceorder+', to='booking.order'),
        ),
    ]
