# Generated by Django 4.2.5 on 2024-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('usermanage', models.BooleanField(default=False, verbose_name='User Management')),
                ('clientmanage', models.BooleanField(default=False, verbose_name='Client Management')),
                ('rolmanage', models.BooleanField(default=False, verbose_name='Role Management')),
                ('commanage', models.BooleanField(default=False, verbose_name='Company Management')),
                ('warmanage', models.BooleanField(default=False, verbose_name='Warehouse Management')),
                ('evemanage', models.BooleanField(default=False, verbose_name='Event Management')),
                ('promanage', models.BooleanField(default=False, verbose_name='Product Management')),
                ('docmanage', models.BooleanField(default=False, verbose_name='Document Management')),
                ('invmanage', models.BooleanField(default=False, verbose_name='Invoice Management')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
