# Generated by Django 4.2.5 on 2024-01-04 19:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanedproduct',
            name='status',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('DEFECTIVE', 'Defective'), ('MISSING', 'Missing'), ('OKAY_RETURNED', 'Okay & Returned')], default='IN_HOUSE', max_length=255),
        ),
    ]
