# Generated by Django 4.2.5 on 2024-01-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_loanedproduct_status'),
        ('inventory', '0002_warehouse_slug_alter_loanedproduct_status'),
    ]

    operations = [
    ]
