# Generated by Django 4.2.5 on 2024-01-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_merge_20240106_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
    ]
