# Generated by Django 4.2.5 on 2024-01-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_merge_20240108_1335'),
        ('inventory', '0004_remove_warehouseproduct_product_delete_warehouse_and_more'),
    ]

    operations = [
    ]
