# Generated by Django 4.2.5 on 2024-02-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20240110_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
