# Generated by Django 4.2.5 on 2024-02-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category_slug_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
