# Generated by Django 4.2.5 on 2024-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
