# Generated by Django 4.2.5 on 2024-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('barcoded', 'Barcoded'), ('non-barcoded', 'Non Barcoded')], default='barcoded', max_length=20),
        ),
    ]
