# Generated by Django 4.2.5 on 2024-01-25 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_merge_20240110_0852'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_day', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=2047)),
                ('location', models.CharField(max_length=2047)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Hold', 'Hold'), ('Ready_to_pack', 'Ready To Pack'), ('Packed', 'Packed'), ('On_site', 'On Site'), ('Returned', 'Returned'), ('Ready_to_invoice', 'Ready To Invoice'), ('Invoiced', 'Invoiced'), ('Paid', 'Paid')], default='Quote', max_length=255)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('labor', models.BooleanField(default=False)),
                ('labor_details', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ManyToManyField(blank=True, to='booking.event')),
                ('items', models.ManyToManyField(blank=True, to='booking.orderitem')),
            ],
        ),
    ]
