# Generated by Django 4.2.5 on 2024-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_event_description_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business'), ('Familyk', 'Family'), ('Holiday', 'Holiday'), ('ETC', 'ETC')], default='ETC', max_length=1023),
        ),
    ]
