# Generated by Django 4.2.5 on 2024-01-28 06:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('street', models.CharField(max_length=255)),
                ('houseNo', models.CharField(max_length=255)),
                ('postal', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='United States', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.CharField(choices=[('Dryhire', 'Dryhire'), ('Band', 'band'), ('Production', 'production')], default='Dryhire', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client'),
        ),
    ]
