# Generated by Django 4.2.5 on 2024-01-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_client_rename_title_event_name_event_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='project',
            new_name='project_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='label',
        ),
    ]
