# Generated by Django 4.2.5 on 2024-01-28 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_rename_project_event_project_type_remove_event_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2555),
            preserve_default=False,
        ),
    ]
