# Generated by Django 4.2.5 on 2024-01-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_account_manager_event_event_manager_and_more'),
        ('booking', '0009_company_client_company'),
    ]

    operations = [
    ]
