# Generated by Django 4.2.5 on 2024-01-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_merge_20240129_1153'),
        ('booking', '0010_merge_20240129_1238'),
    ]

    operations = [
    ]
