# Generated by Django 4.2.5 on 2024-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_merge_20240130_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Inquiry', 'Inquiry'), ('Concept', 'Concept'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Prepped', 'Prepped'), ('On Location', 'On Location'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
    ]
