# Generated by Django 4.2.5 on 2024-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_event_notes_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Inquiry', 'Inquiry'), ('Concept', 'Concept'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Prepped', 'Prepped'), ('On Location', 'On Location'), ('Returned', 'Returned')], default='Pending', max_length=50, null=True),
        ),
    ]
