# Generated by Django 4.2.5 on 2024-03-10 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_rename_count_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('hold', 'Hold'), ('ready_to_pack', 'Ready To Pack'), ('packed', 'Packed'), ('on_site', 'On Site'), ('returned', 'Returned'), ('ready_to_invoice', 'Ready To Invoice'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='quote', max_length=255),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French')], max_length=100)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='booking.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.event'),
        ),
    ]
