# Generated by Django 4.2.5 on 2024-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_event_status_orderitem_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('hold', 'Hold'), ('ready_to_pack', 'Ready To Pack'), ('packed', 'Packed'), ('on_site', 'On Site'), ('returned', 'Returned'), ('ready_to_invoice', 'Ready To Invoice'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='quote', max_length=255),
        ),
    ]
