# Generated by Django 4.2.5 on 2024-03-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_item_remove_warehouseproduct_available_quantity_and_more'),
        ('booking', '0018_order_primary_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='primary_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_order_primary_warehouse+', to='warehouses.warehouse'),
        ),
    ]
