# Generated by Django 4.2.5 on 2024-03-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_item_remove_warehouseproduct_available_quantity_and_more'),
        ('booking', '0019_alter_order_primary_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='w_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouseproduct'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('hold', 'Hold'), ('ready_to_pack', 'Ready To Pack'), ('packed', 'Packed'), ('on_site', 'On Site'), ('returned', 'Returned'), ('ready_to_invoice', 'Ready To Invoice'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='quote', max_length=255, null=True),
        ),
    ]
