# Generated by Django 4.2.5 on 2024-04-30 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_order_scanned_items_alter_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='duoson_address',
            field=models.CharField(default='Office 149, 450 South Brand Brooklyn San Diego County, CA 91905, USA', max_length=1000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='duoson_contact',
            field=models.CharField(default='+1 (123) 456 7891, +44 (876) 543 2198', max_length=1000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, default='It was a pleasure working with you and your team. We hope you will keep us in mind for future projects. Thank You!', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='thanks_note',
            field=models.CharField(blank=True, default='Thanks for your business', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], default='English', max_length=100),
        ),
    ]
