# Generated by Django 4.2.5 on 2024-05-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_invoice_discount_invoice_duoson_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='American Bank', max_length=1000)),
                ('country', models.CharField(default='American Bank', max_length=1000)),
                ('iban', models.CharField(default='American Bank', max_length=1000)),
                ('swift_code', models.CharField(default='American Bank', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='duoson_address',
            field=models.CharField(default='Office 149, 450 South Brand Brooklyn, San Diego County, CA 91905, USA', max_length=1000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.paymentaccount'),
        ),
    ]
