# Generated by Django 4.2.5 on 2024-05-02 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_paymentaccount_alter_invoice_duoson_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_price',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='bank_name',
            field=models.CharField(default='Canada Bank', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='country',
            field=models.CharField(default='Canada', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='iban',
            field=models.CharField(default='ETD95476213874685', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='swift_code',
            field=models.CharField(default='BR91905', max_length=1000),
        ),
    ]
