# Generated by Django 4.2.5 on 2024-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0008_alter_event_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('postal', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='United States', max_length=255)),
                ('clients', models.ManyToManyField(blank=True, related_name='companies', to='booking.client')),
            ],
        ),
    ]
