# Generated by Django 4.2.5 on 2024-01-06 17:26

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_warehouseproduct_product_delete_warehouse_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='warehouse-1', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
                ('reservered_qunatity', models.IntegerField(blank=True, null=True)),
                ('damaged_quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(blank=True, to='warehouses.warehouseproduct'),
        ),
    ]
