# Generated by Django 4.2.5 on 2024-01-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouse_slug_warehouseproduct_warehouse_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseproduct',
            old_name='reservered_qunatity',
            new_name='reserved_quantity',
        ),
    ]
