# Generated by Django 4.2.5 on 2024-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_rename_reservered_qunatity_warehouseproduct_reserved_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('damaged', 'Damaged'), ('reserved', 'Reserved')], default='available', max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='damaged_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='items',
            field=models.ManyToManyField(blank=True, to='warehouses.item'),
        ),
    ]
