# Generated by Django 4.2.5 on 2024-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_item_remove_warehouseproduct_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='warehouses.warehouseproduct'),
        ),
    ]
