# Generated by Django 4.2.5 on 2024-03-30 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_alter_warehouse_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='barcoded', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
