# Generated by Django 4.2.5 on 2024-03-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_item_count_item_item_type_item_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
    ]
