# Generated by Django 4.2.5 on 2024-04-07 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_remove_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from+', to='warehouses.warehouse', verbose_name='from')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.item')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse')),
            ],
        ),
    ]
