# Generated by Django 4.2.5 on 2024-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transfered', 'Transfered')], default='pending', max_length=20),
        ),
    ]
