# Generated by Django 4.2.5 on 2024-04-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0009_transfers_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfers',
            new_name='Transfer',
        ),
    ]
