# Generated by Django 4.2.5 on 2024-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_rename_transfers_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
