# Generated by Django 4.2.5 on 2024-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0011_transfer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
