# Generated by Django 4.2.5 on 2024-04-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_item_type'),
        ('warehouses', '0013_item_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='transfer.items+', to='warehouses.item'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='trans_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.item'),
        ),
    ]
